#Set the base image
FROM ubuntu:14.04

# File Author / Maintainer
MAINTAINER bjg

# Update the sources list
RUN apt-get update

# Update the sources list
RUN apt-get -y upgrade

# Expose listener port
EXPOSE 5000
